dependencies:
  - python=3.6.5
  - tika==1.24
  - regex==2.2.1
  - nltk==3.3
  - functools==0.5
  - sqlite3==2.6.0
  - tensorflow==1.9.0
  - pandas==0.23.3
  - numpy==1.14.4
  - sklearn==0.0